# Standard MQTT Listener (TCP) - Backend/C++ Clients
listener 9883
protocol mqtt

# WebSocket Listener (Browser/React)
listener 9003
protocol websockets

# Security (Dev Only)
allow_anonymous true

# Persistence
persistence true
persistence_location /var/lib/mosquitto/

# Logging
log_dest stdout
log_type all
